Hometask1
NaylRush/smart-home-2021 pull request #1
Opened 2021-03-10 14:55 UTC by NaylRush

2021-03-10 18:48 UTC, a-ivanov requested changes

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private static void listenToEvents(SmartHome smartHome) {
Нарушение SRP: выделите цикл обработки в отдельный класс.

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            List<EventProcessor> eventProcessors = Arrays.asList(
Никакой логики не должно быть в `main`: здесь только конфигурация компонентов (создание объектов, запуск цикла обработки).

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>      private static SensorEvent getNextSensorEvent() {
Нарушение SRP: выделите генератор событий в отдельный класс.

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/JsonSmartHomeWriter.java
> +    public void write(SmartHome smartHome) {
`@Override`

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +        smartHouseWriter.write(smartHome);
`house`/`home` - надо выбрать что-то одно.

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +    List<CommandType> processEvent(SensorEvent event);
Отправка команд - это, скорее, деталь реализации конкретного обработчика (одни обработчики только обновляют состояние данных дома, другие - дополнительно отправляют команды датчикам дома).
Здесь в абстракции вы заставляете имплементации возвращать пустые списки команд, клиентов - использовать их.
Я бы сказал, что здесь нарушен ISP.

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventProcessor.java
> +                if (room.getName().equals(smartHome.getHallRoomName())) {
Нарушение SRP: обработка сценариев - в отдельном обработчике.

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventProcessor.java
> +                if (room.getName().equals(smartHome.getHallRoomName())) {
Я бы передал название комнаты-гостинной полем в эту имплементацию обработчика, чем добавлял нужный только в одном месте геттер в доменный класс `SmartHome`.

2021-03-10 18:48 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    // Is it need?
No, you actually don't need this method. Remove the commented code.

2021-03-11 14:03 UTC, NaylRush commented
@a-ivanov исправил

2021-03-14 19:14 UTC, a-ivanov requested changes

2021-03-14 19:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +    protected final Map<SensorEventType, EventHandler> eventHandlerByEventType;
Зачем так усложнять? У вас уже несколько уровней наследования для такой простой задачи.
Уберите ненужные мапы, перенесите всю логику обработки в классы обработчиков. Этот класс сделайте интерфейсом.

2021-03-14 19:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +    private static SmartHome createSomeSmartHome() {
По заданию необходимо читать состояние дома из файла. Для этого должен быть интерфейс с реализацией.

2021-03-14 19:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            event = EventGenerator.getNextSensorEvent();
Перенесите цикл обработки в отдельный класс.

2021-03-14 19:14 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorClosedHandler.java
> +        String hallRoomName = "hall";
Отдельный обработчик.

2021-03-15 13:20 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +    private static SmartHome createSomeSmartHome() {
Не понимаю, что не так/что нужно сделать
SmartHomeReader/Writer уже написаны

2021-03-16 06:15 UTC, a-ivanov requested changes

2021-03-16 06:15 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorClosedCommandGenerator.java
> +public class DoorClosedCommandGenerator {
Замените этот класс на ещё один обработчик `EventHandler` для сценария закрытия двери. Сейчас у вас обработчик событий двери связан со сценариями.

2021-03-17 05:24 UTC, a-ivanov requested changes

2021-03-17 05:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeEventHandler.java
> +        for (Class<? extends EventProcessor> eventProcessorClass : eventProcessorClasses) {
Зачем все это?.. Ну вот совсем сложно понять, что тут вообще происходит. Сделайте просто список инстансов обработчиков. Рефлексия сложна для понимания, 100% не требуется для решения такой простой задачи. KISS. KISS принцип.

2021-03-17 15:38 UTC, a-ivanov requested changes

2021-03-17 15:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorClosedHandler.java
> +public class HallDoorClosedHandler implements EventHandler {
Сделайте этот класс Processor. Сейчас он у вас не используется в приложении. Команду по тушению света можно отправлять через отдельный интерфейс `CommandSender ` с реализацией, которая просто печатает в консоль (как было в исходной версии кода).

2021-03-18 11:22 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/HallDoorClosedHandler.java
> +public class HallDoorClosedHandler implements EventHandler {
Не понял "Сделайте этот класс Processor."

2021-03-18 16:19 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/HallDoorClosedHandler.java
> +public class HallDoorClosedHandler implements EventHandler {
Я понял. Вы во pr #2 написали

2021-03-22 04:57 UTC, a-ivanov approved these changes

2021-03-22 04:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventProcessor.java
> +                        CommandProducer commandProducer = new LightOffCommandProducer();
Опять же нарушение DIP, создайте в main и передавайте сюда через конструктор.

2021-03-22 15:16 UTC, merged