Hometask2
NaylRush/smart-home-2021 pull request #2
Opened 2021-03-16 16:03 UTC by NaylRush

2021-03-17 05:31 UTC, a-ivanov requested changes

2021-03-17 05:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      public Collection<Room> getRooms() {
Это метод необходимо удалить, мы не хотим привязывать клиентов к внутренней структуре дома.

2021-03-17 05:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        for (Room room : getRooms()) {
Дом тоже можно обработать.

2021-03-17 05:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventProcessor.java
> +                eventHandlerList.add(new HallDoorClosedHandler());
Просто сделайте отдельный обработчик для сценария, как обработчик для двери. Уберите отсюда обработку сценария, это независимые друг от друга задачи. SRP. Тогда и `executeHandlers` станет проще.

2021-03-17 05:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventHandler.java
> +public interface EventHandler {
Зачем нужна ещё одна сущность? Разве `Action` не сможет выполнять эту работу? Чем меньше сущностей для выполнении задачи (без потери других качеств кода), тем лучше.

2021-03-17 15:57 UTC, a-ivanov requested changes
Удалите неиспользуемые /ненужные классы из проекта.

2021-03-17 15:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        List<EventProcessor> eventProcessors = Arrays.asList(
Здесь должен быть обработчик события сценария входной двери.

2021-03-17 15:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightEventProcessor.java
> +    private void handleCommandTypeList(SmartHome smartHome, List<CommandType> commandTypeList) {
Не нужно усложнять. Если обработчик должен отправить команду дому, он может вызывать command sender. Пустые private методы точно не нужны. Удалите его.

2021-03-17 15:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightEventProcessor.java
> +                eventHandlerList.add(new LightOnHandler(event));
Вот здесь запускайте в доме execute (нужный Action). Можно не создавать отдельный класс, используйте лямбды. Удалите классы *Handler, там ещё зачем-то дублируется логика проверки типа события.

2021-03-17 15:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/LightEventProcessor.java
> +        return executeHandlers(smartHome, eventHandlerList);
Это лишнее.

2021-03-19 00:23 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/LightEventProcessor.java
> +                eventHandlerList.add(new LightOnHandler(event));
Без Handler'ов выглядит плохо, потому что у меня получается лямбда в 10 строк

2021-03-22 05:04 UTC, a-ivanov approved these changes

2021-03-22 05:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorClosedHandler.java
> +public class DoorClosedHandler implements Action {
Лучше называть имплементацию по типу интерфейса. Здесь это DoorCloseAction.

2021-03-22 05:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventProcessor.java
> +                CommandProducer commandProducer = new LightOffCommandProducer();
Как в 1 дз: передавайте инстанс через конструктор.

2021-03-22 05:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallDoorEventProcessor.java
> +        HallRoomDoorsAction hallRoomDoorsAction = new HallRoomDoorsAction(hallRoomName);
Оригинальное решение, но можно ведь короче все сделать внутри этого процессора. Так будет меньше сущностей, проще и быстрее читать код.

2021-03-22 15:59 UTC, merged