Hometask3
NaylRush/smart-home-2021 pull request #3
Opened 2021-03-24 22:50 UTC by NaylRush

2021-03-30 16:02 UTC, a-ivanov requested changes

2021-03-30 16:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeEventHandlerWithAlarmSystem.java
> +        this.alarmSystem = new AlarmSystem(code);
Передавайте из main, DIP.

2021-03-30 19:41 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/InactiveAlarmSystemState.java
> +public class InactiveAlarmSystemState extends AlarmSystemState{
Так это же выключенная сигнализация

2021-03-30 19:50 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/InactiveAlarmSystemState.java
> +public class InactiveAlarmSystemState extends AlarmSystemState{
Хотя у меня есть косяк, что включённая не переводит сигнализацию в панику

2021-03-30 20:29 UTC, NaylRush commented
@a-ivanov исправил

2021-03-31 04:37 UTC, a-ivanov approved these changes

2021-03-31 04:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AlarmSystemState.java
> +public interface AlarmSystemState {
А где метод по переводу сразу в тревожное состояние как в задании?

2021-03-31 15:44 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/AlarmSystemState.java
> +public interface AlarmSystemState {
Пропустил. Сейчас добавлю

2021-03-31 16:04 UTC, NaylRush commented on src/main/java/ru/sbt/mipt/oop/AlarmSystemState.java
> +public interface AlarmSystemState {
Добавил. Теперь через сигнализацию можно вызвать метод panic(), который включит сигнализацию, и без кода можно будет её отключить

2021-03-31 16:20 UTC, merged