Hometask4
naylrush/smart-home-2021 pull request #4
Opened 2021-04-01 01:08 UTC by NaylRush

2021-04-01 01:11 UTC, NaylRush commented
Сигнализация должна работать? И можно ли как я либу использовать? Потому что я не особо увидел смысл использовать паттерн *адаптер*, в частности, тот же `SensorEventType` текстом выглядит лучше. Не уверен, как надо было бы сделать.

2021-04-05 05:51 UTC, a-ivanov requested changes
Доделайте адаптер. Сигнализация должна продолжать работать.

2021-04-05 05:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/ApplicationConfiguration.java
> +        List<EventHandler> eventHandlers = Arrays.asList(
См. Гайд, обработчики в отдельных бинах.

2021-04-05 05:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +public record DoorEventHandler(SmartHome smartHome) implements EventHandler {
Нет, по заданию вы не должны менять код обработчиков из предыдущих дз, а именно менять их интерфейс. В этом и суть применения шаблона адаптера. У вас есть сторонний интерфейс и вы создаёте класс, который импоементирует новый интерфейс и переводит вызовы апи нового в старое апи.

2021-04-16 18:04 UTC, naylrush commented
Я отрефаторил код в мастере (и пофиксил пару штук), но по смыслу там ничего не поменялось

2021-04-20 13:42 UTC, a-ivanov requested changes

2021-04-20 13:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/event/SensorEventAdapter.java
> +                .replace("Is", "_")
Слишком вербозно и хрупко, используйте, например, мапу.

2021-04-20 13:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/configurations/ApplicationConfiguration.java
> +    List<EventHandler> getSensorEventHandlers() {
Просто удалите этот бин, тогда все LightEventHandler, DoorEventHandler, итд. сразу соберутся фреймворком в список в бине getAdaptedSensorEventHandlers.

2021-04-20 13:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/configurations/ApplicationConfiguration.java
> +    SensorEventsManager getSensorEventsManager(List<com.coolcompany.smarthome.events.EventHandler> eventHandlers) {
Удалите get, обсуждали в группе.

2021-04-22 06:52 UTC, a-ivanov approved these changes

2024-06-22 21:50 UTC, merged